
## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clkin]

## switches
set_property  PACKAGE_PIN  V17 [get_ports {wxyz[0]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {wxyz[0]}]
set_property  PACKAGE_PIN  V16 [get_ports {wxyz[1]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {wxyz[1]}]
set_property  PACKAGE_PIN  W16 [get_ports {wxyz[2]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {wxyz[2]}]
set_property  PACKAGE_PIN  W17 [get_ports {wxyz[3]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {wxyz[3]}]
set_property  PACKAGE_PIN  W15 [get_ports {wxyz[4]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {wxyz[4]}]
set_property  PACKAGE_PIN  V15 [get_ports {wxyz[5]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {wxyz[5]}]
set_property  PACKAGE_PIN  W14 [get_ports {wxyz[6]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {wxyz[6]}]
set_property  PACKAGE_PIN  W13 [get_ports {wxyz[7]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {wxyz[7]}]

# 7 segment  display
set_property  PACKAGE_PIN  W7 [get_ports {D[0]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {D[0]}]
set_property  PACKAGE_PIN  W6 [get_ports {D[1]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {D[1]}]
set_property  PACKAGE_PIN  U8 [get_ports {D[2]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {D[2]}]
set_property  PACKAGE_PIN  V8 [get_ports {D[3]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {D[3]}]
set_property  PACKAGE_PIN  U5 [get_ports {D[4]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {D[4]}]
set_property  PACKAGE_PIN  V5 [get_ports {D[5]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {D[5]}]
set_property  PACKAGE_PIN  U7 [get_ports {D[6]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {D[6]}]

# Anode  pins  for 7-segment  display:
set_property  PACKAGE_PIN  U2 [get_ports {an[0]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {an[0]}]
set_property  PACKAGE_PIN  U4 [get_ports {an[1]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {an[1]}]
set_property  PACKAGE_PIN  V4 [get_ports {an[2]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {an[2]}]
set_property  PACKAGE_PIN  W4 [get_ports {an[3]}]
    set_property  IOSTANDARD  LVCMOS33 [get_ports {an[3]}]
